<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Sub Department Master"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="96.543">
  <properties />
            <testcase name="Edit_Record" time="8.523" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData">
                <failure type="java.lang.AssertionError"
                  message="expected : [Record Updated Successfully] but Found : [Sub Department Name already exists]"
              >
<![CDATA[java.lang.AssertionError: expected : [Record Updated Successfully] but Found : [Sub Department Name already exists]
  org.testng.Assert.fail(Assert.java:94)
  pom.TestBase.CommonMethods.Test_Edit_Record(CommonMethods.java:160)
  pom.ObjectPages.uiActions.SubDepartmentMaster.Test_EditRecord(SubDepartmentMaster.java:113)
  Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData.Edit_Record(TC016_SubDepartmentMasterUploadData.java:102)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:773)
  org.testng.TestRunner.run(TestRunner.java:623)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="Target_Page" time="61.447" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData" />
                <testcase name="Data_Upload" time="10.027" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData" />
                <testcase name="Login" time="1.453" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData" />
                <testcase name="Data_Upload" time="11.725" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData" />
                <testcase name="AddNew_Button" time="3.368" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData" />
      
</testsuite>
