<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OSO-DTP-057" name="Sub Department Master" tests="6" failures="1" timestamp="16 Nov 2017 05:17:44 GMT" time="158.986" errors="0">
  <testcase name="Login" time="1.453" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData"/>
  <testcase name="Target_Page" time="61.447" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData"/>
  <testcase name="AddNew_Button" time="3.368" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData"/>
  <testcase name="Data_Upload" time="11.725" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData"/>
  <testcase name="Data_Upload" time="10.027" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData"/>
  <testcase name="Edit_Record" time="8.523" classname="Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData">
    <failure type="java.lang.AssertionError" message="expected : [Record Updated Successfully] but Found : [Sub Department Name already exists]">
      <![CDATA[java.lang.AssertionError: expected : [Record Updated Successfully] but Found : [Sub Department Name already exists]
	at pom.TestBase.CommonMethods.Test_Edit_Record(CommonMethods.java:160)
	at pom.ObjectPages.uiActions.SubDepartmentMaster.Test_EditRecord(SubDepartmentMaster.java:113)
	at Module.OrganizationalSetup.TC016_SubDepartmentMasterUploadData.Edit_Record(TC016_SubDepartmentMasterUploadData.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Edit_Record -->
</testsuite> <!-- Sub Department Master -->
