<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.OrganizationalSetup.TC021_BankMasterUploadData" tests="5" failures="2" timestamp="16 Nov 2017 05:49:36 GMT" time="137.066" errors="0">
  <testcase name="Data_Upload" time="17.468" classname="Module.OrganizationalSetup.TC021_BankMasterUploadData">
    <failure type="java.lang.AssertionError" message="Expected : [Record Saved Successfully.] But Found : [Bank Code already exists]">
      <![CDATA[java.lang.AssertionError: Expected : [Record Saved Successfully.] But Found : [Bank Code already exists]
	at org.testng.Assert.fail(Assert.java:94)
	at Module.OrganizationalSetup.TC021_BankMasterUploadData.Data_Upload(TC021_BankMasterUploadData.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Data_Upload -->
  <testcase name="AddNew_Button" time="5.999" classname="Module.OrganizationalSetup.TC021_BankMasterUploadData"/>
  <testcase name="Edit_Record" time="10.524" classname="Module.OrganizationalSetup.TC021_BankMasterUploadData">
    <failure type="java.lang.AssertionError" message="expected : [Record Updated Successfully.] but Found : [Please Enter Bank Code .]">
      <![CDATA[java.lang.AssertionError: expected : [Record Updated Successfully.] but Found : [Please Enter Bank Code .]
	at org.testng.Assert.fail(Assert.java:94)
	at pom.TestBase.CommonMethods.Test_Edit_Record(CommonMethods.java:160)
	at pom.ObjectPages.uiActions.BankMaster.Test_EditRecord(BankMaster.java:127)
	at Module.OrganizationalSetup.TC021_BankMasterUploadData.Edit_Record(TC021_BankMasterUploadData.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Edit_Record -->
  <testcase name="Login" time="3.799" classname="Module.OrganizationalSetup.TC021_BankMasterUploadData"/>
  <testcase name="Target_Page" time="99.276" classname="Module.OrganizationalSetup.TC021_BankMasterUploadData"/>
</testsuite> <!-- Module.OrganizationalSetup.TC021_BankMasterUploadData -->
